# Generated by Django 3.2.9 on 2022-03-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ents', '0002_auto_20220212_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichment',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='ents.KeyWord'),
        ),
        migrations.AlterField(
            model_name='enrichment',
            name='photo',
            field=models.ImageField(default='', upload_to='enrichments/'),
        ),
    ]
