# Generated by Django 3.2.9 on 2022-03-17 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ents', '0003_auto_20220314_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichment',
            name='photo',
            field=models.ImageField(default='', upload_to='enrichments/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
