# Generated by Django 3.2.9 on 2026-08-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ents', '0004_alter_enrichment_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrichment',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='KeyWord',
        ),
    ]
