# Generated by Django 5.2.17 on 2026-09-18 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ents', '0005_remove_keyword'),
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo.itemcategory'),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='is_food',
            field=models.BooleanField(default=False),
        ),
    ]
