# Generated by Django 5.2.17 on 2026-09-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ents', '0006_enrichment_category_enrichment_is_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichment',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='used_in', to='ents.enrichment'),
        ),
    ]
