# Generated by Django 5.2.17 on 2026-09-23 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ents', '0007_enrichment_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichment',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='enrichments/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
