# Generated by Django 5.2.17 on 2026-09-18 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ents', '0005_remove_keyword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ASG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ASG',
                'verbose_name_plural': 'ASGs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'item categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reinforcer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='zoo.asg')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('asg', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ASGApprovedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=500)),
                ('rate', models.CharField(blank=True, max_length=100)),
                ('asg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_assignments', to='zoo.asg')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asg_assignments', to='ents.enrichment')),
            ],
            options={
                'ordering': ['asg', 'item'],
                'unique_together': {('asg', 'item')},
            },
        ),
        migrations.AddField(
            model_name='asg',
            name='approved_items',
            field=models.ManyToManyField(blank=True, related_name='asgs', through='zoo.ASGApprovedItem', to='ents.enrichment'),
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('behavior_type', models.CharField(choices=[('maintenance', 'Maintenance Behavior'), ('new', 'New Behavior')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'behavior_type')},
            },
        ),
        migrations.AddField(
            model_name='asg',
            name='maintenance_behaviors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'behavior_type': 'maintenance'}, related_name='asgs_maintenance', to='zoo.behavior'),
        ),
        migrations.AddField(
            model_name='asg',
            name='new_behaviors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'behavior_type': 'new'}, related_name='asgs_new', to='zoo.behavior'),
        ),
        migrations.AddField(
            model_name='asg',
            name='behavior_goals',
            field=models.ManyToManyField(blank=True, related_name='asgs', to='zoo.behaviorgoal'),
        ),
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('do_score', models.IntegerField(blank=True, choices=[(0, '0 - No Response'), (1, '1 - Low Response'), (2, '2 - Medium Response'), (3, '3 - High Response')], null=True)),
                ('io_score', models.IntegerField(blank=True, choices=[(0, '0 - No Evidence of Response'), (1, '1 - Low Evidence of Response'), (2, '2 - Medium Evidence of Response'), (3, '3 - High Evidence of Response')], null=True)),
                ('gbs_score', models.CharField(blank=True, choices=[('G', 'G - Goal behavior achieved'), ('A', 'A - Appropriate response, but not goal behavior'), ('I', 'I - Inappropriate response'), ('N', 'N - No response'), ('U', 'U - Unable to evaluate')], max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_entries', to='zoo.animal')),
                ('asg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='zoo.asg')),
                ('behavior_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo.behaviorgoal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendar_entries', to='ents.enrichment')),
            ],
            options={
                'verbose_name_plural': 'calendar entries',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='asg',
            name='reinforcers',
            field=models.ManyToManyField(blank=True, related_name='asgs', to='zoo.reinforcer'),
        ),
        migrations.AddField(
            model_name='asg',
            name='special_concerns',
            field=models.ManyToManyField(blank=True, related_name='asgs', to='zoo.specialconcern'),
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('keepers', models.ManyToManyField(blank=True, related_name='strings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(blank=True, max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('last_training_string', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo.string')),
            ],
        ),
        migrations.AddField(
            model_name='asg',
            name='string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asgs', to='zoo.string'),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session_length_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('overall_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('aggression_level', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('appetite_level', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='zoo.asg')),
                ('reinforcers_used', models.ManyToManyField(blank=True, related_name='training_sessions', to='zoo.reinforcer')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.behavior')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_scores', to='zoo.trainingsession')),
            ],
            options={
                'ordering': ['behavior'],
                'unique_together': {('session', 'behavior')},
            },
        ),
    ]
