# Generated by Django 5.2.17 on 2026-09-18 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_supervisor_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='reinforcers_used',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='reinforcer_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='zoo.reinforcer'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='reinforcer_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='zoo.reinforcer'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='reinforcer_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='zoo.reinforcer'),
        ),
    ]
