# Generated by Django 5.2.17 on 2026-09-18 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_remove_trainingsession_reinforcers_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='divisions',
            field=models.ManyToManyField(blank=True, related_name='supervisors', to='zoo.division'),
        ),
        migrations.AddField(
            model_name='string',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strings', to='zoo.division'),
        ),
    ]
