# Generated by Django 5.2.17 on 2026-09-18 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_administrator_group_and_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['name'], 'verbose_name': 'individual animal', 'verbose_name_plural': 'individual animals'},
        ),
        migrations.AlterModelOptions(
            name='asg',
            options={'ordering': ['name'], 'verbose_name': 'animal', 'verbose_name_plural': 'animals'},
        ),
        migrations.AlterModelOptions(
            name='asgapproveditem',
            options={'ordering': ['asg', 'item'], 'verbose_name': 'approved item', 'verbose_name_plural': 'approved items'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='asg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='zoo.asg', verbose_name='animal'),
        ),
        migrations.AlterField(
            model_name='asgapproveditem',
            name='asg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_assignments', to='zoo.asg', verbose_name='animal'),
        ),
        migrations.AlterField(
            model_name='calendarentry',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_entries', to='zoo.animal', verbose_name='individual animal'),
        ),
        migrations.AlterField(
            model_name='calendarentry',
            name='asg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='zoo.asg', verbose_name='animal'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='asg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='zoo.asg', verbose_name='animal'),
        ),
    ]
