# Generated by Django 5.2.17 on 2026-09-18 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0009_finish_calendar_training_split'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['name'], 'verbose_name': 'animal choice', 'verbose_name_plural': 'animal choices'},
        ),
        migrations.AlterModelOptions(
            name='asg',
            options={'ordering': ['name'], 'verbose_name': 'calendar', 'verbose_name_plural': 'calendars'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='asg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='zoo.asg', verbose_name='calendar'),
        ),
        migrations.AlterField(
            model_name='asgapproveditem',
            name='asg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_assignments', to='zoo.asg', verbose_name='calendar'),
        ),
        migrations.AlterField(
            model_name='calendarentry',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_entries', to='zoo.animal'),
        ),
        migrations.AlterField(
            model_name='calendarentry',
            name='asg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='zoo.asg', verbose_name='calendar'),
        ),
    ]
