# Generated by Django 5.2.17 on 2026-09-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ents', '0006_enrichment_category_enrichment_is_food'),
        ('zoo', '0010_calendar_verbose_names'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asgapproveditem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asgapproveditem',
            name='is_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='asgapproveditem',
            unique_together={('asg', 'item', 'is_food')},
        ),
    ]
