# Generated by Django 5.2.17 on 2026-09-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0011_approveditem_is_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarentry',
            name='initials',
            field=models.CharField(blank=True, max_length=2, verbose_name='init'),
        ),
    ]
